name: Build and push
on:
  push:
    branches: [main]
    paths:
      - "packages/shelter/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: "uwu/shelter-builds"
          path: "builds"
          token: ${{ secrets.ALY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: packages/shelter
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build
        run: npm run build

      - name: Push builds
        run: |
          rm $GITHUB_WORKSPACE/builds/* || true
          cp -r dist/* $GITHUB_WORKSPACE/builds || true
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push
